import { ASOF, nexa, nexaIncome, bankLicensingNote } from "./companies.js"

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 })

/** Default scenario used in copy and FAQ. */
export const SCENARIO = { volumeM: 30, avgLoan: 400000 }

export function compareFaqs(c) {
  const faqs = [
    {
      q: "How does loan officer comp work at NEXA?",
      a: `On NEXA's standard plan, NEXA keeps ${nexa.standardRetainBps} bps per loan and you keep the rest of your compensation. NEXA also offers NEXA100, a path to keeping 100% — Andres can walk you through the current terms and whether you'd qualify.`,
    },
  ]
  if (c.kind === "broker") {
    const gross = nexa.defaultGrossBps
    const theirs = Math.round(c.income({ volumeM: SCENARIO.volumeM, grossBps: gross, avgLoan: SCENARIO.avgLoan }))
    const ours = Math.round(nexaIncome({ volumeM: SCENARIO.volumeM, grossBps: gross }))
    faqs.push({
      q: `Do loan officers keep more at ${c.short} or NEXA?`,
      a:
        theirs > ours
          ? `On fees alone, ${c.short} can come out ahead: at $${SCENARIO.volumeM}M a year in $${SCENARIO.avgLoan / 1000}K loans and ${gross} bps gross comp, that's about ${usd.format(theirs)} at ${c.short} versus about ${usd.format(ours)} on NEXA's standard plan, based on published fees as of ${ASOF}. Compare what else each company offers, and run your own numbers in the calculator.`
          : `At $${SCENARIO.volumeM}M a year in $${SCENARIO.avgLoan / 1000}K loans and ${gross} bps gross comp, that's about ${usd.format(ours)} on NEXA's standard plan versus ${usd.format(theirs)} at ${c.short}, based on published fees as of ${ASOF}. Run your own numbers in the calculator.`,
    })
  }
  if (c.kind === "bank") {
    faqs.push({ q: `Do I need a state license to leave ${c.short} for NEXA?`, a: bankLicensingNote })
  }
  faqs.push({
    q: `What happens to my pipeline and clients if I leave ${c.short}?`,
    a: "Loans in process and leads generated by your current employer generally stay with them, and many loan officers have non-solicitation or other agreements to review before moving. Andres will help you plan the timing so the transition is as smooth as possible.",
  })
  return faqs
}

